apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.name }} component created by Backstage
  tags:
    - naftiko
    - capability
    {%- if not values.empty %}
    {%- for adapter in values.adapters %}
    - ${{ adapter | lower | replace(" ", "-") }}
    {%- endfor %}
    {%- endif %}
  links:
    - url: https://github.com/${{ values.repoOwner }}/${{ values.repoName }}
      title: View repository on GitHub
      icon: github
  annotations:
    backstage.io/source-location: url:https://github.com/${{ values.repoOwner }}/${{ values.repoName }}/blob/main/
    github.com/project-slug: ${{ values.repoOwner }}/${{ values.repoName }}
spec:
  type: service
  lifecycle: experimental
  owner: user:guest
  {%- if values.consumes and values.consumes | length > 0 %}
  consumesApis:
    {%- for consumesEntry in values.consumes %}
    - ${{ consumesEntry.catalogEntityRef }}
    {%- endfor %}
  {%- endif %}
